//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDetail
    {
        public int ticketDetailID { get; set; }
        public int ticketID { get; set; }
        public int customerID { get; set; }
        public int saleTicketID { get; set; }
        public int timeFrameID { get; set; }
        public int ticketTypeID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SaleTicket SaleTicket { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual TicketType TicketType { get; set; }
        public virtual TimeFrame TimeFrame { get; set; }
    }
}
